In [1]:
import numpy as np
import pandas as pd

In [2]:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

In [3]:
print(temperatures_w1.shape)
print(temperatures_w1.dtype)
print(temperatures_w1.size)
print(temperatures_w1.ndim)

(7,)
float64
7
1

In [4]:
Fahrenheit=[]
for i in range(1,8,1):
  Fahren=float(input(f'enter the {i}st element:'))
  Fahrenheits=(Fahren*1.8)+32
  Fahrenheit.append(Fahrenheits)

print(Fahrenheit)

enter the 1st element:22.5
enter the 2st element:25.3
enter the 3st element:20.8
enter the 4st element:23.4
enter the 5st element:26.1
enter the 6st element:24.8
enter the 7st element:21.9
[72.5, 77.53999999999999, 69.44, 74.12, 78.98, 76.64, 71.42]

In [5]:
print(Fahrenheit)
temperatures_Fahrenheit=np.array(Fahrenheit)
print(temperatures_Fahrenheit.max())
print(temperatures_Fahrenheit.min())
print(temperatures_Fahrenheit.mean())

[72.5, 77.53999999999999, 69.44, 74.12, 78.98, 76.64, 71.42]
78.98
69.44
74.37714285714286

In [6]:
print(temperatures_w1[0:3])
print(temperatures_w1[5:7])
temperatures_w1[2:5]

[22.5 25.3 20.8]
[24.8 21.9]

array([20.8, 23.4, 26.1])

In [7]:
print(temperatures.shape)
print(temperatures.dtype)
print(temperatures.size)
print(temperatures.ndim)

(2, 7)
float64
14
2

In [8]:
print(temperatures[0][5:7])
print(temperatures[1][5:7])

[24.8 21.9]
[22.8 20.1]

In [12]:
Marks=[95, 92, 89, 85, 80]
Custom_Indices=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
marks=pd.Series(Marks,index=Custom_Indices)
print(marks.iat[0])
marks.at['Rank1']

95

np.int64(95)

In [14]:
print(marks.loc['Rank1':'Rank3'])
print(marks.iloc[3])

Rank1    95
Rank2    92
Rank3    89
dtype: int64
85

In [15]:
marks>90

Rank1     True
Rank2     True
Rank3    False
Rank4    False
Rank5    False
dtype: bool

In [18]:
marks.loc['Rank1']=100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [19]:
marks.drop('Rank5', inplace=True)
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [27]:
for mark in Marks:
  CGPA=mark/10
  print(CGPA)

9.5
9.2
8.9
8.5
8.0

In [127]:
Transactions={'Transaction ID':[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
              'Product Category':['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing','Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
              'Region':['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South','North'],
              'Amount':[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
              }
Transactions_DF=pd.DataFrame(Transactions,index=[101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
Transactions_DF

     Transaction ID Product Category Region  Amount
101             101      Electronics  North     200
102             102         Clothing  South     150
103             103      Electronics  North     300
104             104        Furniture   East     450
105             105         Clothing   West     200
106             106      Electronics  North     250
107             107        Furniture   East     300
108             108         Clothing   West     180
109             109        Furniture  South     350
110             110      Electronics  North     400

In [128]:
print(Transactions_DF.shape)
print(Transactions_DF.columns)
print(Transactions_DF.dtypes)
print(Transactions_DF.tail)

(10, 4)
Index(['Transaction ID', 'Product Category', 'Region', 'Amount'], dtype='object')
Transaction ID       int64
Product Category    object
Region              object
Amount               int64
dtype: object
<bound method NDFrame.tail of      Transaction ID Product Category Region  Amount
101             101      Electronics  North     200
102             102         Clothing  South     150
103             103      Electronics  North     300
104             104        Furniture   East     450
105             105         Clothing   West     200
106             106      Electronics  North     250
107             107        Furniture   East     300
108             108         Clothing   West     180
109             109        Furniture  South     350
110             110      Electronics  North     400>

In [129]:
print(Transactions_DF.head)
print(Transactions_DF.info())

<bound method NDFrame.head of      Transaction ID Product Category Region  Amount
101             101      Electronics  North     200
102             102         Clothing  South     150
103             103      Electronics  North     300
104             104        Furniture   East     450
105             105         Clothing   West     200
106             106      Electronics  North     250
107             107        Furniture   East     300
108             108         Clothing   West     180
109             109        Furniture  South     350
110             110      Electronics  North     400>
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 101 to 110
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10 non-null     int64
 1   Product Category  10 non-null     object
 2   Region            10 non-null     object
 3   Amount            10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 400.0+ bytes
None

In [130]:
Transactions_DF.iloc[7:10]

     Transaction ID Product Category Region  Amount
108             108         Clothing   West     180
109             109        Furniture  South     350
110             110      Electronics  North     400

In [131]:
Transactions_DF.loc[(Transactions_DF['Amount']>200) & (Transactions_DF['Region']=='North')]

     Transaction ID Product Category Region  Amount
103             103      Electronics  North     300
106             106      Electronics  North     250
110             110      Electronics  North     400

In [132]:
Transactions_DF.loc[(Transactions_DF['Amount']>200) & (Transactions_DF['Region']=='South')]

     Transaction ID Product Category Region  Amount
109             109        Furniture  South     350

In [133]:
Transactions_DF['Product Category'].count()

np.int64(10)

In [134]:
Transactions_DF['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [135]:
Transactions_DF.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [137]:
Transactions_DF.iat[1,3]=165
Transactions_DF

     Transaction ID Product Category Region  Amount
101             101      Electronics  North     200
102             102         Clothing  South     165
103             103      Electronics  North     300
104             104        Furniture   East     450
105             105         Clothing   West     200
106             106      Electronics  North     250
107             107        Furniture   East     300
108             108         Clothing   West     180
109             109        Furniture  South     350
110             110      Electronics  North     400

In [138]:
Discount_list=[]
for amount in range(1,11,1):
  amount=float(input('Enter the your regional Amount:'))
  Discount=amount-(amount*0.10)
  Discount_list.append(Discount)
  print(Discount_list)

Transactions_DF['Discount']=Discount_list
Transactions_DF

Enter the your regional Amount:200
[180.0]
Enter the your regional Amount:165
[180.0, 148.5]
Enter the your regional Amount:300
[180.0, 148.5, 270.0]
Enter the your regional Amount:450
[180.0, 148.5, 270.0, 405.0]
Enter the your regional Amount:200
[180.0, 148.5, 270.0, 405.0, 180.0]
Enter the your regional Amount:250
[180.0, 148.5, 270.0, 405.0, 180.0, 225.0]
Enter the your regional Amount:300
[180.0, 148.5, 270.0, 405.0, 180.0, 225.0, 270.0]
Enter the your regional Amount:180
[180.0, 148.5, 270.0, 405.0, 180.0, 225.0, 270.0, 162.0]
Enter the your regional Amount:350
[180.0, 148.5, 270.0, 405.0, 180.0, 225.0, 270.0, 162.0, 315.0]
Enter the your regional Amount:400
[180.0, 148.5, 270.0, 405.0, 180.0, 225.0, 270.0, 162.0, 315.0, 360.0]

     Transaction ID Product Category Region  Amount  Discount
101             101      Electronics  North     200     180.0
102             102         Clothing  South     165     148.5
103             103      Electronics  North     300     270.0
104             104        Furniture   East     450     405.0
105             105         Clothing   West     200     180.0
106             106      Electronics  North     250     225.0
107             107        Furniture   East     300     270.0
108             108         Clothing   West     180     162.0
109             109        Furniture  South     350     315.0
110             110      Electronics  North     400     360.0

In [141]:
Transactions_DF.drop(109,axis=0,inplace=True)
Transactions_DF

     Transaction ID Product Category Region  Amount  Discount
101             101      Electronics  North     200     180.0
102             102         Clothing  South     165     148.5
103             103      Electronics  North     300     270.0
104             104        Furniture   East     450     405.0
105             105         Clothing   West     200     180.0
106             106      Electronics  North     250     225.0
107             107        Furniture   East     300     270.0
108             108         Clothing   West     180     162.0
110             110      Electronics  North     400     360.0

In [142]:
Transactions_DF.drop('Discount',axis=1,inplace=True)
Transactions_DF

     Transaction ID Product Category Region  Amount
101             101      Electronics  North     200
102             102         Clothing  South     165
103             103      Electronics  North     300
104             104        Furniture   East     450
105             105         Clothing   West     200
106             106      Electronics  North     250
107             107        Furniture   East     300
108             108         Clothing   West     180
110             110      Electronics  North     400